version: 2.1

jobs:
  install:
    docker:
    - image: circleci/node
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - persist_to_workspace:
          root: workspace
          paths:
            - node_modules

  test:
    docker:
      - image: weboaks/node-karma-protractor-chrome
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/node_modules
    - run:
        name: test
        command: 'npm run test:ci'

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/node_modules
      - run:
          name: build
          command: 'npm run build:lib'

#workflows:
#  version: 2
#  everything:
#    jobs:
#      - install
#      - test
#          requires:
#            - install
#      - build:
#          requires:
#            - install
#            - test
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only:
#                - master


#  release:
#    docker:
#      - image: circleci/node
#    branches:
#      only:
#        - master
#    steps:
#      - checkout
#      - run:
#          name: install
#          command: 'npm install'
#      - run:
#          name: build
#          command: 'npm run build:lib'
#      - run:
#          name: publish-demo-site
#          command: 'npm run publish:pages'
#      - run:
#          name: publish
#          command: 'npm run publish'
