version: 2.1

defaults: &defaults
  docker:
  - image: circleci/node
  working_directory: ~/app

jobs:
  install:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - restore_cache:
        keys:
        - npm-cache-{{ .Branch }}-{{ checksum \"package-lock.json\" }}
        - npm-cache-{{ .Branch }}
        - npm-cache-
    - run: npm install
    - save_cache:
        key: npm-cache-{{ .Branch }}-{{ checksum \"package-lock.json\" }}
        paths: node_modules
    - persist_to_workspace:
        root: .
        paths: .

  test:
    <<: *defaults
    docker:
    - image: weboaks/node-karma-protractor-chrome
    steps:
    - checkout
    - run: npm install
    - run: npm run test:ci

  build:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - run: npm run build:lib
    - persist_to_workspace:
        root: .
        paths: .

  publish_pages:
    <<: *defaults
    environment:
      GH_TOKEN: $GH_TOKEN
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - run: npm run publish:pages

  deploy:
    <<: *defaults
    environment:
      GH_TOKEN: $GH_TOKEN
      NPM_TOKEN: $NPM_TOKEN
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - run:
        name: Login to npm
        command: echo \"//registry.npmjs.org/:_authToken=${NPM_TOKEN}\" >> ~/app/.npmrc
    - run: cat ~/app/.npmrc
    #    - run: npm install dot-json
    #    - run: dot-json dist/contexr/package.json version $CIRCLE_TAG
    #    - run: cat ~/app/dist/contexr/package.json
    - run:
        name: Publish library
        command: npm run publish --access=public

workflows:
  version: 2.1
  test_and_release:
    jobs:
    - install:
        filters:
          tags:
            only: /.*/
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        requires:
        - install
        - test
    #    - publish_pages:
    #        requires:
    #          - build
    #        filters:
    #          branches:
    #            only: master
    - deploy:
        requires:
        - install
        - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
