version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node
  working_directory: /app

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - persist_to_workspace:
          root: /
          paths:
            - node_modules
  test:
    <<: *defaults
    docker:
    - image: weboaks/node-karma-protractor-chrome
    steps:
      - checkout
      - attach_workspace:
          at: /node_modules
      - run:
          name: test
          command: 'npm run test:ci'
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /node_modules
      - run:
          name: build
          command: 'npm run build:lib'
      - persist_to_workspace:
          root: /
          paths:
            - dist

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - install
      - test:
          requires:
            - install
#      - build:
#          requires:
#            - install
#            - test
#          filters:
#            tags:
#              only:
#                - master

