version: 2.1

jobs:
  test:
    docker:
      - image: weboaks/node-karma-protractor-chrome
    steps:
    - checkout
    - run:
        name: install
        command: 'npm install'
    - run:
        name: test
        command: 'npm run test:ci'

  build:
    docker:
    - image: circleci/node
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: build
          command: 'npm run build:lib'
