version: 2.1

defaults: &defaults
  docker:
  - image: circleci/node
  working_directory: ~/app

jobs:
  install:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - run: npm install
    - persist_to_workspace:
        root: .
        paths: .

  test:
    <<: *defaults
    docker:
    - image: weboaks/node-karma-protractor-chrome
    steps:
    - checkout
    - run: npm install
    - run: npm run test:ci

  build:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - run: npm run build:lib
    - persist_to_workspace:
        root: .
        paths: .

  publish_pages:
    <<: *defaults
    environment:
      GH_TOKEN: $GH_TOKEN
    steps:
    - checkout
    - attach_workspace:
        at: ~/app
    - run: npm run publish:pages

workflows:
  version: 2.1
  test_and_release:
    jobs:
    - install
    - test
    - build:
        requires:
        - install
        - test
    - publish_pages:
        requires:
          - build
        filters:
          branches:
            only: master
