version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node
  working_directory: ~/app

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app/node_modules
      - restore_cache:
          keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache-
      - run: npm install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    docker:
    - image: weboaks/node-karma-protractor-chrome
    steps:
      - checkout
      - attach_workspace:
          at: ~/app/node_modules
      - run: npm run test:ci
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app/node_modules
      - run: npm run build:lib
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
            - test
          filters:
            tags:
              only:
                - master

