name: Test & Build

on: push

jobs:
    cypress-component-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cypress run (component)
              uses: cypress-io/github-action@v6
              with:
                build: npm run build
                start: npm start
                browser: chrome
                component: true